[package]
name = "penumbra-proto-compiler"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
ibc-proto = { version = "0.40.0" }
ics23 = "0.11.3"
pbjson = "0.6"
pbjson-build = "0.6"
pbjson-types = "0.6"
prost = "0.12.3"
prost-build = "0.12.3"
prost-types = "0.12"
tempfile = "3"
tonic-build = { version = "0.10.0", features = ["cleanup-markdown"] }
